FROM eclipse-temurin:21-jre
WORKDIR /opt/datomic
COPY datomic-pro /opt/datomic
# Add postgres driver
RUN find lib -name "postgresql-*.jar" || curl -o lib/postgresql-42.7.3.jar https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar
COPY docker-transactor.properties /opt/datomic/config/transactor.properties
EXPOSE 4334 4335 4336
ENTRYPOINT ["./bin/transactor", "config/transactor.properties"]